#!/usr/bin/env python3
"""Regenerate tools/agent/names.py from the decomp's enums.

Reads the action-state, character and stage enums out of the headers under
src/melee and writes plain dicts {value: name}, so the bridge tools can print
"Wait" instead of 14 without importing any C. Run it again after the decomp
renames something:

    python3 tools/agent/gen_names.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "names.py"

# (dict name, header, enum typedef name, member prefix stripped from names)
ENUMS = [
    ("MOTION", "src/melee/ft/kinds/ftCommon/forward.h", "ftCommon_MotionState", "ftCo_MS_"),
    ("FIGHTER_KIND", "src/melee/ft/forward.h", "FighterKind", "Ft_Kind_"),
    ("CHARACTER_KIND", "src/melee/ft/forward.h", "CharacterKind", "CKind_"),
    ("STAGE_KIND", "src/melee/gr/forward.h", "StKind", "St_Kind_"),
    ("SCENE_KIND", "src/melee/gm/forward.h", "GameSceneKind", "GS_"),
]


def parse_enum(text, name):
    """Members of `typedef enum X {...} name;` as {value: member}, first name wins."""
    end = re.search(r"\}\s*" + re.escape(name) + r"\s*;", text)
    if end is None:
        raise SystemExit(f"enum {name} not found")
    start = text.rfind("typedef enum", 0, end.start())
    body = text[text.index("{", start) + 1 : end.start()]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    values = {}
    by_name = {}
    nxt = 0
    for item in body.split(","):
        item = item.strip()
        if not item:
            continue
        if "=" in item:
            member, expr = (s.strip() for s in item.split("=", 1))
            expr = expr.strip()
            if expr in by_name:
                val = by_name[expr]
            else:
                val = int(expr, 0)
        else:
            member, val = item, nxt
        by_name[member] = val
        values.setdefault(val, member)
        nxt = val + 1
    return values


def main():
    lines = [
        '"""Decomp enum names for the agent bridge tools.',
        "",
        "Generated by tools/agent/gen_names.py from the headers under src/melee;",
        'do not edit by hand."""',
        "",
    ]
    for dict_name, header, enum_name, prefix in ENUMS:
        values = parse_enum((ROOT / header).read_text(encoding="utf-8"), enum_name)
        lines.append(f"# {enum_name} ({header})")
        lines.append(f"{dict_name} = {{")
        for val in sorted(values):
            member = values[val]
            if val < 0 or member.endswith("_Count") or member.endswith("_Max"):
                continue
            short = member[len(prefix):] if member.startswith(prefix) else member
            lines.append(f"    {val}: {short!r},")
        lines.append("}")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
